[package]
name = "mapping_like_storage_contract"
version = "0.1.0"
edition = "2024_07"

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.11.4"

[dev-dependencies]
cairo_test = "2.11.4"
